[server]
host = "localhost"
port = 8000

[redis]
uri = "redis://localhost/0"

[logging]
version = 1

    [logging.formatters.fmt]
    "()" = "logging.Formatter"
    format = "%(module)s %(levelname)s %(asctime)s: %(message)s"
    datefmt = "%H:%M:%S.%s"

    [logging.handlers.console]
    "()" = "logging.StreamHandler"
    stream = "ext://sys.stdout"
    formatter = "fmt"

    [logging.loggers.domains_counter]
    handlers = [ "console",]
    level = "DEBUG"
    propagate = false

